<?php

return [
    'brands' => [
        'Audi',
        'BMW',
        'Citroën',
        'Dacia',
        'Fiat',
        'Ford',
        'Honda',
        'Hyundai',
        'Mercedes-Benz',
        'Mitsubishi',
        'Nissan',
        'Peugeot',
        'Suzuki',
        'Toyota',
        'Volkswagen',
        'Volvo',
    ],
    'categories' => [
        'Ligeiro de Passageiros',
        'Ligeiro de Mercadorias',
    ],
    'colors' => [
        'Branco e outros',
        'Preto e outros',
        'Azul e outros',
        'Vermelho e outros',
        'Verde e outros',
        'Roxo e outros',
        'Amarelo e outros',
        'Cinza e outros',
        'Laranja e outros',
        'Castanho e outros',
    ],
    'proprietaries' => [
        'Roboplan',
        'Robowork',
        'EuroBic',
        'Santander',
        'Consumer',
        'LeasePlan(Portugal)',
        'Roboplan / Robowork',
        'Locarent(Portugal)',
        'Não pertence à frota/Foi Vendido',
    ],
    'fuel_types' => [
        'assigning' => [
            'Gasolina',
            'Gasóleo',
            'Híbrido (Gasolina)',
            'Híbrido (Gasóleo)',
        ],
        'refuelling' => [
            'AdBlue',
            'Gasolina',
            'Gasolina Premium',
            'Gasóleo',
            'Gasóleo Premium',
        ],
    ],
];
